In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("darkgrid")

### Column names are assigned

In [5]:
columns = ["engine_id", "time_cycles", "opr_setting_1", "opr_setting_2", "opr_setting_3"] + [f's{i}' for i in range(1,22)]
df = pd.read_csv("train_FD001.txt", sep=' ', header=None, names=columns)
df

         engine_id  time_cycles  opr_setting_1  opr_setting_2  opr_setting_3  \
1   1      -0.0007      -0.0004          100.0         518.67         641.82
    2       0.0019      -0.0003          100.0         518.67         642.15
    3      -0.0043       0.0003          100.0         518.67         642.35
    4       0.0007       0.0000          100.0         518.67         642.35
    5      -0.0019      -0.0002          100.0         518.67         642.37
...            ...          ...            ...            ...            ...
100 196    -0.0004      -0.0003          100.0         518.67         643.49
    197    -0.0016      -0.0005          100.0         518.67         643.54
    198     0.0004       0.0000          100.0         518.67         643.42
    199    -0.0011       0.0003          100.0         518.67         643.23
    200    -0.0032      -0.0005          100.0         518.67         643.85

              s1       s2     s3     s4      s5  ...      s12     s13   s14  \
1   1    1589.70  1400.60  14.62  21.61  554.36  ...  8138.62  8.4195  0.03
    2    1591.82  1403.14  14.62  21.61  553.75  ...  8131.49  8.4318  0.03
    3    1587.99  1404.20  14.62  21.61  554.26  ...  8133.23  8.4178  0.03
    4    1582.79  1401.87  14.62  21.61  554.45  ...  8133.83  8.3682  0.03
    5    1582.85  1406.22  14.62  21.61  554.00  ...  8133.80  8.4294  0.03
...          ...      ...    ...    ...     ...  ...      ...     ...   ...
100 196  1597.98  1428.63  14.62  21.61  551.43  ...  8137.60  8.4956  0.03
    197  1604.50  1433.58  14.62  21.61  550.86  ...  8136.50  8.5139  0.03
    198  1602.46  1428.18  14.62  21.61  550.94  ...  8141.05  8.5646  0.03
    199  1605.26  1426.53  14.62  21.61  550.68  ...  8139.29  8.5389  0.03
    200  1600.38  1432.14  14.62  21.61  550.79  ...  8137.33  8.5036  0.03

         s15   s16    s17    s18      s19  s20  s21
1   1    392  2388  100.0  39.06  23.4190  NaN  NaN
    2    392  2388  100.0  39.00  23.4236  NaN  NaN
    3    390  2388  100.0  38.95  23.3442  NaN  NaN
    4    392  2388  100.0  38.88  23.3739  NaN  NaN
    5    393  2388  100.0  38.90  23.4044  NaN  NaN
...      ...   ...    ...    ...      ...  ...  ...
100 196  397  2388  100.0  38.49  22.9735  NaN  NaN
    197  395  2388  100.0  38.30  23.1594  NaN  NaN
    198  398  2388  100.0  38.44  22.9333  NaN  NaN
    199  395  2388  100.0  38.29  23.0640  NaN  NaN
    200  396  2388  100.0  38.37  23.0522  NaN  NaN

[20631 rows x 26 columns]

### Finding maximum cycle for each number that they can reach and adding to table

In [7]:
max_cycles = df.groupby('engine_id')['time_cycles'].max().reset_index()
max_cycles.columns = ['engine_id', 'max_cycles']

df = pd.merge(df, max_cycles, on = 'engine_id', how = 'left')
df

,engine_id,time_cycles,opr_setting_1,opr_setting_2,opr_setting_3,s1,s2,s3,s4,s5,...,s13,s14,s15,s16,s17,s18,s19,s20,s21,max_cycles
0,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,21.61,554.36,...,8.4195,0.03,392,2388,100.0,39.06,23.4190,NaN,NaN,0.0006
1,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,21.61,553.75,...,8.4318,0.03,392,2388,100.0,39.00,23.4236,NaN,NaN,0.0006
2,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,21.61,554.26,...,8.4178,0.03,390,2388,100.0,38.95,23.3442,NaN,NaN,0.0005
3,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,21.61,554.45,...,8.3682,0.03,392,2388,100.0,38.88,23.3739,NaN,NaN,0.0005
4,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,21.61,554.00,...,8.4294,0.03,393,2388,100.0,38.90,23.4044,NaN,NaN,0.0005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,21.61,551.43,...,8.4956,0.03,397,2388,100.0,38.49,22.9735,NaN,NaN,0.0005
20627,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,21.61,550.86,...,8.5139,0.03,395,2388,100.0,38.30,23.1594,NaN,NaN,0.0005
20628,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,21.61,550.94,...,8.5646,0.03,398,2388,100.0,38.44,22.9333,NaN,NaN,0.0006
20629,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,21.61,550.68,...,8.5389,0.03,395,2388,100.0,38.29,23.0640,NaN,NaN,0.0006
20630,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,21.61,550.79,...,8.5036,0.03,396,2388,100.0,38.37,23.0522,NaN,NaN,0.0005

### RUL(Remaining Useful Life) calculation for each engine

In [8]:
# RUL = (max cycle) - (current cycle)
df['RUL'] = df['max_cycles'] - df['time_cycles']

df = df.drop('max_cycles', axis = 1)
print(df[['engine_id', 'time_cycles', 'RUL']].head(10))

   engine_id  time_cycles     RUL
0    -0.0007      -0.0004  0.0010
1     0.0019      -0.0003  0.0009
2    -0.0043       0.0003  0.0002
3     0.0007       0.0000  0.0005
4    -0.0019      -0.0002  0.0007
5    -0.0043      -0.0001  0.0006
6     0.0010       0.0001  0.0004
7    -0.0034       0.0003  0.0003
8     0.0008       0.0001  0.0005
9    -0.0033       0.0001  0.0004